version: '2'

services:
    elasticsearch:
        build: ./.docker/elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - "./data:/usr/share/elasticsearch/data"
            
    kibana:
        build: ./.docker/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - "./.docker/redis/redis.conf:/etc/redis/redis.conf"

    logstash:
        build: ./.docker/logstash
        volumes:
            - "./sample:/tmp/data/"
        ports:
            - "5044:5044"
        links:
            - elasticsearch

    mysql:
        image: "mysql:5.7.19"
        restart: always
        ports: 
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        volumes:
            - ./data/mysql-data:/var/lib/mysql
            - './.docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'

    app:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "3000:3000"
        command: "npm start"
        links:
            - elasticsearch
            - mysql
            - redis

    listener:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        command: "npm run listen"
        links:
            - elasticsearch
            - mysql
            - redis
